### ISSUE TITLE
No module named 'oft.model.edoft'

### ISSUE THREAD

**Issue by piaodangdang** [tom-roddick/oft#1]
I run the train.py  ,there is a error like the title , Is there a problem in my env ? I modify the file in oft/model/oftnet.py ,I delete  "from .edoft import ExplicitDepthOFT" , Are there some problem with this Modify

**Comment by tom-roddick** [comment]
Thanks for pointing this out, there isn't a problem with your environment, the file edoft.py is part of some old code which was missing from the repo.

**Comment by tom-roddick** [comment]
Fixed by commit 4b6073a
