### ISSUE TITLE
Binary mask in Encoder is incorrect

### ISSUE THREAD

**Issue by ayushbaid** [tom-roddick/oft#10]
In the Encoder class, the encode function returns a binary mask which is then used in some loss computation. The current mask is all ones and I think there is a bug in this line: https://github.com/tom-roddick/oft/blob/master/oft/data/encoder.py#L51

> `mask = indices >= 0`

If I replace this line with `mask = indices > 0`, the mask contains 1 where the object is present and 0 otherwise. The paper mentions that position loss, dimension loss, etc. are computed only on grid locations which intersect with ground truth objects. Hence it is essential the mask is correct.

**Comment by tom-roddick** [comment]
Hi Ayushbad, thanks for raising, this is indeed a bug! Commit 38886ea should fix the issue.
