### ISSUE TITLE
RuntimeError: Loss diverged :()

### ISSUE THREAD

**Issue by koala719** [tom-roddick/oft#11]
Since there is only one camera. The calib.txt is:
P0: 6.37994953564521e+02 0.000000000000e+00 3.01236221058740e+02 0.000000000000e+02 0.000000000000e+00 6.00262324131012e+02 2.27931532293491e+02 0.000000000000e+02 0.000000000000e+00 0.000000000000e+00 1.000000000000e+00 0.000000000000e+02
Tr: -5.1912446e-03 8.5375016e-03 -4.025496e-04 -1.6381511968e+02 -3.0239484e-03 1.3941179e-03 -9.4293251e-03 -9.1064823408e+02 -7.9941676e-03 -5.0167222e-03 -3.3054171e-03 9.66718621095e+03
If the last column of P0 is all 0, the loss will be NAN.
How to solve this problem？

**Comment by alfinnurhalim** [comment]
how did you solve this problem?

**Comment by IAMShashankk** [comment]
@koala719 @tom-roddick Any inputs on this? @koala719 How did you solve this?
