### ISSUE TITLE
Running inference

### ISSUE THREAD

**Issue by paruliansaragi** [tom-roddick/oft#2]
Hi,

First of all great work, 

Do you have any intention of creating a script that can run inference? Or if you did how would you go about doing it here? I've been working on it for a bit and I am getting stuck.

Thanks!

**Comment by chris-doe** [comment]
Hi, 

did you had any success with that so far? I've been trying to decode the network output heads but at the end I was facing issues when projecting the inferred bbox... 

Would really be interested in a inference script with included NMS and decoding stage. Nonetheless, great and interesting work! 

Thank you!

**Comment by tom-roddick** [comment]
Hi there, thanks for the comments! Sorry for the delay, I haven't had chance to make changes to the code recently but I'll try and add an inference script in over the next few days.

**Comment by tom-roddick** [comment]
The latest commit c7d3ced22a30216c87e28a39ef785be820258ddd adds a new `infer.py` script which demonstrates how to decode the predicted bounding boxes and visualise them. Hopefully this answers your questions, closing the issue for now. Thanks!
