### ISSUE TITLE
why multiply img_height * img_width * 0.25 when calculating area?

### ISSUE THREAD

**Issue by kaixinbear** [tom-roddick/oft#8]
https://github.com/tom-roddick/oft/blob/2deed80f7c292c3cc4eaf8dfde544e28e32a0dde/oft/model/oft.py#L46

`area = ((bbox_corners[..., 2:] - bbox_corners[..., :2]).prod(dim=-1)` I think that's the code for the computing area of bbox;why do you add img_height * img_width * 0.25? and what's meaning of 0.25?
anyone could do me a favor?

**Comment by kaixinbear** [comment]
It seems to de-normalize `(2 * img_corners / img_size - 1).clamp(-1, 1)`?

**Comment by tom-roddick** [comment]
Hi, that's correct! Pytorch's `grid_sample` function requires the box corner coordinates to be normalised between (-1, 1), so to get the area of the bounding box in pixels it is necessary to un-normalise them by multiplying by `img_height / 2 * img_width / 2`

**Comment by kaixinbear** [comment]
I got it!Thx.
